//
//  PokedexProtocols.swift
//  Pokedex
//
//  Created Michel Torres Alonso on 11/06/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol PokedexWireframeProtocol: AnyObject {
    func goToPokemonDetail(id: Int)
}
//MARK: Presenter -
protocol PokedexPresenterProtocol: AnyObject {
    var pokemons: [Pokemon] { get set }
    var pokemonsFiltered: [Pokemon] { get set }
    
    func getPokemons()
    func showPokemons(pokemons: [Pokemon])
    func searchPokemon(text: String)
    func goToPokemonDetail(index: Int)
    func getPokemonByType(url: String)
    func showErrorMessage()
}

//MARK: Interactor -
protocol PokedexInteractorProtocol: AnyObject {

    var presenter: PokedexPresenterProtocol?  { get set }
    
    func getPokemons(offset: Int, limit: Int)
    func getPokemonByType(url: String)
}

//MARK: View -
protocol PokedexViewProtocol: AnyObject {

  var presenter: PokedexPresenterProtocol?  { get set }
    
    func showPokemons()
    func showErrorMessage()
}
