//
//  PokedexPresenter.swift
//  Pokedex
//
//  Created Michel Torres Alonso on 11/06/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PokedexPresenter: PokedexPresenterProtocol {
    var pokemons: [Pokemon] = []

    weak private var view: PokedexViewProtocol?
    var interactor: PokedexInteractorProtocol?
    private let router: PokedexWireframeProtocol

    init(interface: PokedexViewProtocol, interactor: PokedexInteractorProtocol?, router: PokedexWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func getPokemons() {
        interactor?.getPokemons(offset: pokemons.count, limit: 20)
    }
    
    func showPokemons(pokemons: [Pokemon]) {
        self.pokemons = pokemons
        view?.showPokemons()
    }

}
