//
//  PokemonDetailRouter.swift
//  Pokedex
//
//  Created Michel Torres Alonso on 11/06/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PokemonDetailRouter: PokemonDetailWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(id: Int) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = PokemonDetailViewController(nibName: nil, bundle: nil)
        let interactor = PokemonDetailInteractor()
        let router = PokemonDetailRouter()
        let presenter = PokemonDetailPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        view.pokemonId = id
        
        return view
    }
    
    func goToTypePokemon(_ type: PokemonType) {
        let pokemonSearchView = PokedexRouter.createModule(type: type)
        viewController?.navigationController?.pushViewController(pokemonSearchView, animated: true)
    }
}
